import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from '../components/Footer.jsx';
import { UserProvider } from '@auth0/nextjs-auth0/client';
import { EdgeStoreProvider } from '../../lib/edgestore';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kokan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
        <EdgeStoreProvider>
          <Navbar />
          {children}
          <Footer />
          </EdgeStoreProvider>
        </UserProvider>
      </body>
    </html>
  );
}